# Generated by Django 2.1.7 on 2019-03-26 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190326_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='parent',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
    ]
