# Generated by Django 2.1.7 on 2019-03-26 19:15

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20190326_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Child', models.ForeignKey(null=True, on_delete=courses.models.Course, to='courses.Course')),
            ],
        ),
    ]
