# Generated by Django 2.1.7 on 2019-03-26 19:28

import courses.models
from django.db import migrations, models
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20190326_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField()),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=courses.models.Course, related_name='children', to='courses.Category')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='parent',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=models.AutoField(primary_key=True, serialize=False), to='courses.Category'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('parent', 'slug')},
        ),
    ]
