# Generated by Django 2.1.7 on 2019-03-26 20:20

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20190326_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='courses.Course'),
        ),
    ]
