# Generated by Django 2.1.7 on 2019-03-27 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20190326_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'courses'},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('parent', 'slug')},
        ),
    ]
