version: '3'

services:
  python:
    # image: python:3.4
    build:
      context: .
      dockerfile: docker/prod/python/Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=madzones.settings.prod
      - PYTHONUNBUFFERED=1
    volumes:
      - ./madzones:/madzones
      - static_files:/static_cdn
    ports:
      - 8000:8000
    command: gunicorn -w 4 madzones.wsgi -b 0.0.0.0:8000
  postgres:
    image: postgres:10.3
    environment:
      POSTGRES_USER: madzones
      POSTGRES_DB: madzones
      POSTGRES_PASS: madzones
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  nginx:
    # image: nginx
    build:
      context: .
      dockerfile: docker/prod/nginx/Dockerfile
    volumes:
      - static_files:/static_cdn
    ports:
      - 80:80

volumes:
  pgdata:
  static_files: