# Generated by Django 2.1.7 on 2019-04-22 20:43

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='', max_length=1000)),
                ('option1', models.TextField(default='', max_length=255)),
                ('option2', models.TextField(default='', max_length=255)),
                ('option3', models.TextField(default='', max_length=255)),
                ('option4', models.TextField(default='', max_length=255)),
                ('explanation', models.TextField(default='', max_length=500)),
                ('correct_answer', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Option 1'), (2, 'Option 2'), (3, 'Option 3'), (4, 'Option 4')], max_length=7)),
            ],
        ),
    ]
